INSERT INTO items (id, item_name, zone, wowhead_id)
VALUES  (DEFAULT, 'Bonereaver''s Edge', 'Molten Core', 17076),
        (DEFAULT, 'Eye of Sulfuras', 'Molten Core', 17204),
        (DEFAULT, 'Sulfuron Ingot', 'Molten Core', 17203),
        (DEFAULT, 'Spinal Reaper', 'Molten Core', 17104),
        (DEFAULT, 'Ancient Petrified Leaf', 'Molten Core', 18703),
        (DEFAULT, 'Teebu''s Blazing Longsword', 'Molten Core', 1728),
        (DEFAULT, 'The Eye of Divinity', 'Molten Core', 18646),
        (DEFAULT, 'Azuresong Mageblade', 'Molten Core', 17103),
        (DEFAULT, 'Sash of Mercy', 'Molten Core', 14553),
        (DEFAULT, 'Perdition''s Blade', 'Molten Core', 18816),
        (DEFAULT, 'Robe of Volatile Power', 'Molten Core', 19145),
        (DEFAULT, 'Brutality Blade', 'Molten Core', 18832),
        (DEFAULT, 'Right Half Bindings of the Windseeker', 'Molten Core', 18564),
        (DEFAULT, 'Obsidian Edged Blade', 'Molten Core', 18822),
        (DEFAULT, 'Talisman of Ephemeral Power', 'Molten Core', 18820),
        (DEFAULT, 'Staff of Dominance', 'Molten Core', 18842),
        (DEFAULT, 'Ring of Spell Power', 'Molten Core', 19147),
        (DEFAULT, 'Eskhandar''s Right Claw', 'Molten Core', 18203),
        (DEFAULT, 'Earthshaker', 'Molten Core', 17073),
        (DEFAULT, 'Striker''s Mark', 'Molten Core', 17069),
        (DEFAULT, 'Left Half Bindings of the Windseeker', 'Molten Core', 18563),
        (DEFAULT, 'Drillborer Disk', 'Molten Core', 17066),
        (DEFAULT, 'Core Hound Tooth', 'Molten Core', 18805),
        (DEFAULT, 'Band of Accuria', 'Molten Core', 17063),
        (DEFAULT, 'Cauterizing Band', 'Molten Core', 19140),
        (DEFAULT, 'Aurastone Hammer', 'Molten Core', 17105),
        (DEFAULT, 'Mana Igniting Cord', 'Molten Core', 19136),
        (DEFAULT, 'Quick Strike Ring', 'Molten Core', 18821),
        (DEFAULT, 'Choker of the Fire Lord', 'Molten Core', 18814),
        (DEFAULT, 'Wristguards of Stability', 'Molten Core', 19146),
        (DEFAULT, 'Wild Growth Spaulders', 'Molten Core', 18810),
        (DEFAULT, 'Crown of Destruction', 'Molten Core', 18817),
        (DEFAULT, 'Gutgore Ripper', 'Molten Core', 17071),
        (DEFAULT, 'Malistar''s Defender', 'Molten Core', 17106),
        (DEFAULT, 'Onslaught Girdle', 'Molten Core', 19137),
        (DEFAULT, 'Aged Core Leather Gloves', 'Molten Core', 18823),
        (DEFAULT, 'Sash of Whispered Secrets', 'Molten Core', 18809),
        (DEFAULT, 'Salamander Scale Pants', 'Molten Core', 18875),
        (DEFAULT, 'Shadowstrike', 'Molten Core', 17074),
        (DEFAULT, 'Sorcerous Dagger', 'Molten Core', 18878),
        (DEFAULT, 'Flameguard Gauntlets', 'Molten Core', 19143),
        (DEFAULT, 'Arcanist Crown', 'Molten Core', 16795),
        (DEFAULT, 'Finkle''s Lava Dredger', 'Molten Core', 18803),
        (DEFAULT, 'Blastershot Launcher', 'Molten Core', 17072),
        (DEFAULT, 'Heavy Dark Iron Ring', 'Molten Core', 18879),
        (DEFAULT, 'Arcanist Bindings', 'Molten Core', 16799),
        (DEFAULT, 'Nightslayer Shoulder Pads', 'Molten Core', 16823),
        (DEFAULT, 'Essence of the Pure Flame', 'Molten Core', 18815),
        (DEFAULT, 'Choker of Enlightenment', 'Molten Core', 17109),
        (DEFAULT, 'Pauldrons of Might', 'Molten Core', 16868),
        (DEFAULT, 'Cloak of the Shrouded Mists', 'Molten Core', 17102),
        (DEFAULT, 'Mantle of Prophecy', 'Molten Core', 16816),
        (DEFAULT, 'Netherwind Pants', 'Molten Core', 16915),
        (DEFAULT, 'Medallion of Steadfast Might', 'Molten Core', 17065),
        (DEFAULT, 'Nightslayer Gloves', 'Molten Core', 16826),
        (DEFAULT, 'Fire Runed Grimoire', 'Molten Core', 19142),
        (DEFAULT, 'Shard of the Flame', 'Molten Core', 17082),
        (DEFAULT, 'Crimson Shocker', 'Molten Core', 17077),
        (DEFAULT, 'Belt of Might', 'Molten Core', 16864),
        (DEFAULT, 'Felheart Slippers', 'Molten Core', 16803),
        (DEFAULT, 'Nightslayer Chestpiece', 'Molten Core', 16820),
        (DEFAULT, 'Nightslayer Belt', 'Molten Core', 16827),
        (DEFAULT, 'Girdle of Prophecy', 'Molten Core', 16817),
        (DEFAULT, 'Fireguard Shoulders', 'Molten Core', 19139),
        (DEFAULT, 'Vambraces of Prophecy', 'Molten Core', 16819),
        (DEFAULT, 'Helm of Might', 'Molten Core', 16866),
        (DEFAULT, 'Bloodfang Pants', 'Molten Core', 16909),
        (DEFAULT, 'Giantstalker''s Helmet', 'Molten Core', 16846),
        (DEFAULT, 'Bracers of Might', 'Molten Core', 16861),
        (DEFAULT, 'Felheart Belt', 'Molten Core', 16806),
        (DEFAULT, 'Nightslayer Cover', 'Molten Core', 16821),
        (DEFAULT, 'Felheart Horns', 'Molten Core', 16808),
        (DEFAULT, 'Band of Sulfuras', 'Molten Core', 19138),
        (DEFAULT, 'Arcanist Robes', 'Molten Core', 16798),
        (DEFAULT, 'Felheart Robes', 'Molten Core', 16809),
        (DEFAULT, 'Giantstalker''s Epaulets', 'Molten Core', 16848),
        (DEFAULT, 'Nemesis Leggings', 'Molten Core', 16930),
        (DEFAULT, 'Dragon''s Blood Cape', 'Molten Core', 17107),
        (DEFAULT, 'Manastorm Leggings', 'Molten Core', 18872),
        (DEFAULT, 'Breastplate of Might', 'Molten Core', 16865),
        (DEFAULT, 'Arcanist Belt', 'Molten Core', 16802),
        (DEFAULT, 'Legplates of Wrath', 'Molten Core', 16962),
        (DEFAULT, 'Gauntlets of Might', 'Molten Core', 16863),
        (DEFAULT, 'Robes of Prophecy', 'Molten Core', 16815),
        (DEFAULT, 'Deep Earth Spaulders', 'Molten Core', 18829),
        (DEFAULT, 'Leggings of Transcendence', 'Molten Core', 16922),
        (DEFAULT, 'Sabatons of Might', 'Molten Core', 16862),
        (DEFAULT, 'Giantstalker''s Belt', 'Molten Core', 16851),
        (DEFAULT, 'Felheart Bracers', 'Molten Core', 16804),
        (DEFAULT, 'Boots of Prophecy', 'Molten Core', 16811),
        (DEFAULT, 'Earthfury Helmet', 'Molten Core', 16842),
        (DEFAULT, 'Wristguards of True Flight', 'Molten Core', 18812),
        (DEFAULT, 'Gloves of Prophecy', 'Molten Core', 16812),
        (DEFAULT, 'Nightslayer Bracelets', 'Molten Core', 16825),
        (DEFAULT, 'Seal of the Archmagus', 'Molten Core', 17110),
        (DEFAULT, 'Nightslayer Boots', 'Molten Core', 16824),
        (DEFAULT, 'Felheart Gloves', 'Molten Core', 16805),
        (DEFAULT, 'Arcanist Boots', 'Molten Core', 16800),
        (DEFAULT, 'Circlet of Prophecy', 'Molten Core', 16813),
        (DEFAULT, 'Felheart Shoulder Pads', 'Molten Core', 16807),
        (DEFAULT, 'Cenarion Spaulders', 'Molten Core', 16836),
        (DEFAULT, 'Arcanist Mantle', 'Molten Core', 16797),
        (DEFAULT, 'Flamewaker Legplates', 'Molten Core', 18861),
        (DEFAULT, 'Earthfury Epaulets', 'Molten Core', 16844),
        (DEFAULT, 'Giantstalker''s Breastplate', 'Molten Core', 16845),
        (DEFAULT, 'Judgement Legplates', 'Molten Core', 16954),
        (DEFAULT, 'Giantstalker''s Gloves', 'Molten Core', 16852),
        (DEFAULT, 'Cenarion Belt', 'Molten Core', 16828),
        (DEFAULT, 'Nightslayer Pants', 'Molten Core', 16822),
        (DEFAULT, 'Lawbringer Helm', 'Molten Core', 16854),
        (DEFAULT, 'Cenarion Helm', 'Molten Core', 16834),
        (DEFAULT, 'Cenarion Vestments', 'Molten Core', 16833),
        (DEFAULT, 'Dragonstalker''s Legguards', 'Molten Core', 16938),
        (DEFAULT, 'Arcanist Gloves', 'Molten Core', 16801),
        (DEFAULT, 'Helm of the Lifegiver', 'Molten Core', 18870),
        (DEFAULT, 'Cenarion Boots', 'Molten Core', 16829),
        (DEFAULT, 'Gloves of the Hypnotic Flame', 'Molten Core', 18808),
        (DEFAULT, 'Giantstalker''s Bracers', 'Molten Core', 16850),
        (DEFAULT, 'Stormrage Legguards', 'Molten Core', 16901),
        (DEFAULT, 'Lawbringer Belt', 'Molten Core', 16858),
        (DEFAULT, 'Giantstalker''s Leggings', 'Molten Core', 16847),
        (DEFAULT, 'Arcanist Leggings', 'Molten Core', 16796),
        (DEFAULT, 'Felheart Pants', 'Molten Core', 16810),
        (DEFAULT, 'Cenarion Bracers', 'Molten Core', 16830),
        (DEFAULT, 'Earthfury Belt', 'Molten Core', 16838),
        (DEFAULT, 'Legplates of Might', 'Molten Core', 16867),
        (DEFAULT, 'Lawbringer Spaulders', 'Molten Core', 16856),
        (DEFAULT, 'Core Forged Greaves', 'Molten Core', 18806),
        (DEFAULT, 'Legplates of Ten Storms', 'Molten Core', 16946),
        (DEFAULT, 'Giantstalker''s Boots', 'Molten Core', 16849),
        (DEFAULT, 'Earthfury Vestments', 'Molten Core', 16841),
        (DEFAULT, 'Magma Tempered Boots', 'Molten Core', 18824),
        (DEFAULT, 'Lawbringer Chestguard', 'Molten Core', 16853),
        (DEFAULT, 'Lawbringer Bracers', 'Molten Core', 16857),
        (DEFAULT, 'Pants of Prophecy', 'Molten Core', 16814),
        (DEFAULT, 'Cenarion Leggings', 'Molten Core', 16835),
        (DEFAULT, 'Fireproof Cloak', 'Molten Core', 18811),
        (DEFAULT, 'Sabatons of the Flamewalker', 'Molten Core', 19144),
        (DEFAULT, 'Earthfury Gauntlets', 'Molten Core', 16839),
        (DEFAULT, 'Lawbringer Gauntlets', 'Molten Core', 16860),
        (DEFAULT, 'Earthfury Bracers', 'Molten Core', 16840),
        (DEFAULT, 'Lawbringer Legplates', 'Molten Core', 16855),
        (DEFAULT, 'Lawbringer Boots', 'Molten Core', 16859),
        (DEFAULT, 'Earthfury Boots', 'Molten Core', 16837),
        (DEFAULT, 'Earthfury Legguards', 'Molten Core', 16843),
        (DEFAULT, 'Cenarion Gloves', 'Molten Core', 16831);


