INSERT INTO items (id, item_name, zone, wowhead_id)
VALUES  (DEFAULT, 'Schematic: Spellpower Goggles Xtreme', 'Onyxia''s Layer', 10605),
        (DEFAULT, 'Formula: Enchant Shield - Frost Resistance', 'Onyxia''s Layer', 11224),
        (DEFAULT, 'Plans: Widthorn Mail', 'Onyxia''s Layer', 12691),
        (DEFAULT, 'Plans: Thorium Shield Spike', 'Onyxia''s Layer', 12692),
        (DEFAULT, 'Plans: Thorium Helm', 'Onyxia''s Layer', 12694),
        (DEFAULT, 'Plans: Radiant Boots', 'Onyxia''s Layer', 12697),
        (DEFAULT, 'Plans: Radiant Circlet', 'Onyxia''s Layer', 12702),
        (DEFAULT, 'Plans: Storm Gauntlets', 'Onyxia''s Layer', 12703),
        (DEFAULT, 'Plans: Thorium Leggings', 'Onyxia''s Layer', 12704),
        (DEFAULT, 'Plans: Radiant Leggings', 'Onyxia''s Layer', 12713),
        (DEFAULT, 'Plans: Invulnerable Mail', 'Onyxia''s Layer', 12728),
        (DEFAULT, 'Staff of Hale Magefire', 'Onyxia''s Layer', 13000),
        (DEFAULT, 'Lord Alexander''s Battle Axe', 'Onyxia''s Layer', 13003),
        (DEFAULT, 'Torch of Austen', 'Onyxia''s Layer', 13004),
        (DEFAULT, 'Mass of McGowan', 'Onyxia''s Layer', 13006),
        (DEFAULT, 'Mageflame Cloak', 'Onyxia''s Layer', 13007),
        (DEFAULT, 'Dalewind Trousers', 'Onyxia''s Layer', 13008),
        (DEFAULT, 'Cow King''s Hide', 'Onyxia''s Layer', 13009),
        (DEFAULT, 'Elder Wizard''s Mantle', 'Onyxia''s Layer', 13013),
        (DEFAULT, 'Serathil', 'Onyxia''s Layer', 13005),
        (DEFAULT, 'Assassination Blade', 'Onyxia''s Layer', 13036),
        (DEFAULT, 'Heartseeking Crossbow', 'Onyxia''s Layer', 13040),
        (DEFAULT, 'Twig of the World Tree', 'Onyxia''s Layer', 13047),
        (DEFAULT, 'Wyrmslayer Spaulders', 'Onyxia''s Layer', 13066),
        (DEFAULT, 'Hydralick Armor', 'Onyxia''s Layer', 13067),
        (DEFAULT, 'Sapphirn''s Scale Boots', 'Onyxia''s Layer', 13070),
        (DEFAULT, 'Stonegrip Gauntlets', 'Onyxia''s Layer', 13072),
        (DEFAULT, 'Mugthol''s Helm', 'Onyxia''s Layer', 13073),
        (DEFAULT, 'Direwing Legguards', 'Onyxia''s Layer', 13075),
        (DEFAULT, 'Medallion of Grand Marshal Morris', 'Onyxia''s Layer', 13091),
        (DEFAULT, 'Magiskull Cuffs', 'Onyxia''s Layer', 13107),
        (DEFAULT, 'Sandals of the Insurgent', 'Onyxia''s Layer', 13111),
        (DEFAULT, 'Feathermoon Headdress', 'Onyxia''s Layer', 13113),
        (DEFAULT, 'Spaulders of the Unseen', 'Onyxia''s Layer', 13116),
        (DEFAULT, 'Serpentine Sash', 'Onyxia''s Layer', 13118),
        (DEFAULT, 'Deepfury Bracers', 'Onyxia''s Layer', 13120),
        (DEFAULT, 'Dreamwalker Armor', 'Onyxia''s Layer', 13123),
        (DEFAULT, 'Elven Chain Boots', 'Onyxia''s Layer', 13125),
        (DEFAULT, 'Battlecaller Gauntlets', 'Onyxia''s Layer', 13126),
        (DEFAULT, 'Windrunner Legguards', 'Onyxia''s Layer', 13130),
        (DEFAULT, 'Drakesfire Epaultes', 'Onyxia''s Layer', 13133),
        (DEFAULT, 'Lordly Armguards', 'Onyxia''s Layer', 13135),
        (DEFAULT, 'Serenity Belt', 'Onyxia''s Layer', 13144),
        (DEFAULT, 'Shell Launcher Shotgun', 'Onyxia''s Layer', 13146),
        (DEFAULT, 'Recipe: Transmute Water to Undeath', 'Onyxia''s Layer', 13487),
        (DEFAULT, 'Scale of Onyxia', 'Onyxia''s Layer', 15410),
        (DEFAULT, 'Pattern: Runic Leather Gauntlets', 'Onxyia''s Layer', 15731),
        (DEFAULT, 'Pattern: Wicked Leather Pants', 'Onxyia''s Layer', 15757),
        (DEFAULT, 'Stormrage Cover', 'Onxyia''s Layer', 16900),
        (DEFAULT, 'Bloodfang Hood', 'Onxyia''s Layer', 16908),
        (DEFAULT, 'Netherwind Crown', 'Onxyia''s Layer', 16914),
        (DEFAULT, 'Halo of Transcendence', 'Onxyia''s Layer', 16921),
        (DEFAULT, 'Nemesis Skullcap', 'Onxyia''s Layer', 16929),
        (DEFAULT, 'Dragonstalker''s Helm', 'Onxyia''s Layer', 16939),
        (DEFAULT, 'Helmet of Ten Storms', 'Onxyia''s Layer', 16947),
        (DEFAULT, 'Judgement Crown', 'Onxyia''s Layer', 16955),
        (DEFAULT, 'Helm of Wrath', 'Onxyia''s Layer', 16963),
        (DEFAULT, 'Shard of the Scale', 'Onxyia''s Layer', 17064),
        (DEFAULT, 'Ancient Cornerstone Grimoire', 'Onxyia''s Layer', 17067),
        (DEFAULT, 'Deathbringer', 'Onxyia''s Layer', 17068),
        (DEFAULT, 'Vis''kag the Bloodletter', 'Onxyia''s Layer', 17075),
        (DEFAULT, 'Sapphiron Drape', 'Onxyia''s Layer', 17078),
        (DEFAULT, 'Codex: Prayer of Fortitude', 'Onxyia''s Layer', 17413),
        (DEFAULT, 'Codex: Prayer of Fortitude II', 'Onxyia''s Layer', 17414),
        (DEFAULT, 'Book: Gift of the Wild', 'Onxyia''s Layer', 17681),
        (DEFAULT, 'Book: Gift of the Wild II', 'Onxyia''s Layer', 17683),
        (DEFAULT, 'Onyxia Hide Backpack', 'Onxyia''s Layer', 17966),
        (DEFAULT, 'Eskhandar''s Collar', 'Onxyia''s Layer', 18205),
        (DEFAULT, 'Head of Onyxia', 'Onxyia''s Layer', 18422),
        (DEFAULT, 'Tome of Arcane Brilliance', 'Onxyia''s Layer', 18600),
        (DEFAULT, 'Mature Black Dragon Sinew', 'Onxyia''s Layer', 18705),
        (DEFAULT, 'Ring of Binding', 'Onxyia''s Layer', 18813),
        (DEFAULT, 'Codex: Prayer of Shadow Protection', 'Onxyia''s Layer', 22393),
        (DEFAULT, 'Tome of Frost Ward V', 'Onxyia''s Layer', 22890),
        (DEFAULT, 'Grimoire of Shadow Ward IV', 'Onxyia''s Layer', 22891);